/* eslint-disable import/no-anonymous-default-export */
const en = {
  admin_sidemenu_item_lots: "Lots",
  admin_sidemenu_item_create_lot: "Create Lot",
  admin_sidemenu_item_update_lot: "Update Lot",
  admin_sidemenu_item_shipments: "Shipments",
  admin_sidemenu_item_create_shipment: "Create Shipment",
  admin_sidemenu_item_consult_shipment: "Consult Shipment",
  admin_sidemenu_item_users: "Users",
  admin_sidemenu_item_create_user: "Create User",
  admin_sidemenu_item_update_user: "Update User",
  admin_sidemenu_item_statistics: "Statistics",
  admin_sidemenu_item_settings: "Settings",
  admin_nav_item_settings: "Settings",
  admin_nav_item_profile: "Profile",
  admin_nav_item_logout: "Logout",
  admin_page_create_lot_title: "CreateLot",
  admin_page_create_lot_alert_success: "Lot created successfully",
  admin_page_create_lot_alert_error: "Error creating the lot",
  admin_page_create_lot_input_label_lot_number: "Lot Number",
  admin_page_create_lot_input_placeholder_lot_number: "Enter the lot number",
  admin_page_create_lot_input_label_destination: "Destinations",
  admin_page_create_lot_input_placeholder_destination: "Select the destination",
  admin_page_create_lot_input_label_conveyance: "Conveyance",
  admin_page_create_lot_input_placeholder_conveyance: "Select the conveyance",
  admin_page_create_lot_input_conveyance_option_ship: "Ship",
  admin_page_create_lot_input_conveyance_option_airplane: "Aerial",
  admin_page_create_lot_button_create: "Create",
  admin_page_update_lot_title: "Update Lot",
  admin_page_update_lot: "Lot",
  admin_page_update_lot_input_select_lot: "Select a lot",
  admin_page_update_lot_button_search: "Search",
  admin_page_create_shipment_title: "Create Shipment",
  admin_page_consult_shipment_title: "Consult Shipment",
  admin_page_create_user_title: "Create User",
  admin_page_update_user_title: "Update User",
  admin_page_statistics_title: "Statistics",
  admin_page_settings_title: "Settings",
  admin_text_created_date: "Created on",
  admin_text_created_status: "Status",
  admin_text_created_updated: "Updated on",
  admin_text_created_status_received_on_warehouse: "Received on warehouse",
  admin_text_created_status_on_USA_transit: "On transit in USA",
  admin_text_created_status_on_travel_on_ship: "On travel on ship",
  admin_text_created_status_on_travel_on_airplane: "On travel on airplane",
  admin_text_created_status_on_aduanas: "On customs",
  admin_text_created_status_on_final_transit: "On final transit to destination",
};

const es = {
  admin_sidemenu_item_lots: "Lotes",
  admin_sidemenu_item_create_lot: "Crear Lote",
  admin_sidemenu_item_update_lot: "Actualizar Lote",
  admin_sidemenu_item_shipments: "Envios",
  admin_sidemenu_item_create_shipment: "Crear Envio",
  admin_sidemenu_item_consult_shipment: "Consultar Envio",
  admin_sidemenu_item_users: "Usuarios",
  admin_sidemenu_item_create_user: "Crear Usuario",
  admin_sidemenu_item_update_user: "Actualizar Usuario",
  admin_sidemenu_item_statistics: "Estadisticas",
  admin_sidemenu_item_settings: "Configuraciones",
  admin_nav_item_settings: "Configuraciones",
  admin_nav_item_profile: "Perfil",
  admin_nav_item_logout: "Cerrar Sesión",
  admin_page_create_lot_title: "Crear Lote",
  admin_page_create_lot_alert_success: "Lote creado con exito",
  admin_page_create_lot_alert_error: "Error al crear el lote",
  admin_page_create_lot_input_label_lot_number: "Número de Lote",
  admin_page_create_lot_input_placeholder_lot_number:
    "Ingrese el número de lote",
  admin_page_create_lot_input_label_destination: "Destino",
  admin_page_create_lot_input_placeholder_destination: "Seleccione el destino",
  admin_page_create_lot_input_label_conveyance: "Transporte",
  admin_page_create_lot_input_placeholder_conveyance:
    "Seleccione el tipo de transporte",
  admin_page_create_lot_input_conveyance_option_ship: "Maritimo",
  admin_page_create_lot_input_conveyance_option_airplane: "Aereo",
  admin_page_create_lot_button_create: "Crear",
  admin_page_update_lot_title: "Actualizar Lote",
  admin_page_update_lot: "Lote",
  admin_page_update_lot_input_select_lot: "Seleccione un lote",
  admin_page_update_lot_button_search: "Buscar",
  admin_page_create_shipment_title: "Crear Envio",
  admin_page_consult_shipment_title: "Consultar Envio",
  admin_page_create_user_title: "Crear Usuario",
  admin_page_update_user_title: "Actualizar Usuario",
  admin_page_statistics_title: "Estadisticas",
  admin_page_settings_title: "Configuraciones",
  admin_text_created_date: "Creado el",
  admin_text_created_status: "Estatus",
  admin_text_created_updated: "Actualizado el",
  admin_text_created_status_received_on_warehouse: "Recibido en almacén",
  admin_text_created_status_on_USA_transit: "En transito en USA",
  admin_text_created_status_on_travel_on_ship: "En viaje en barco",
  admin_text_created_status_on_travel_on_airplane: "En viaje en avión",
  admin_text_created_status_on_aduanas: "En aduanas",
  admin_text_created_status_on_final_transit: "En transito final a destino",
};

export { en, es };
