import "./globals.css";

import { Inter } from "next/font/google";
import { LanguageProvider } from "@/context/Language.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Global Control",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
